import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/auth/Provider";
import RecentActivityProvider from "@/components/context/RecentActivityProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <RecentActivityProvider>{children}</RecentActivityProvider>
        </Providers>

        {/* Ionic Icons */}
        <script
          type="module"
          async
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
          nomodule
          async
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        ></script>
      </body>
    </html>
  );
}
