version: '3.8'

services:
  server:
    build: .
    image: server
    container_name: server
    ports:
      - "8000:8000"
    # add any additional configuration for this service
  webhook:
    build:
      context: src/webhook
      dockerfile: Dockerfile
    image: webhook
    container_name: webhook
    ports:
      - "4242:4242"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  ai:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ai
    container_name: ai
    ports:
      - "5000:5000"
    # add any additional configuration for this service


volumes:
  mongodb:
    # add any additional configuration for this service
